// <auto-generated />
using System;
using CoahuilaRelacion.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoahuilaRelacion.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260410161827_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CoahuilaRelacion.Api.Models.Declaracion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaCaptura")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RegistroId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextoDeclaracion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Orden");

                    b.HasIndex("RegistroId");

                    b.ToTable("Declaraciones");
                });

            modelBuilder.Entity("CoahuilaRelacion.Api.Models.DeclaracionCoordenada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeclaracionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fuente")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitud")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitud")
                        .HasColumnType("REAL");

                    b.Property<string>("Observacion")
                        .HasColumnType("TEXT");

                    b.Property<double?>("PrecisionM")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DeclaracionId");

                    b.ToTable("DeclaracionCoordenadas");
                });

            modelBuilder.Entity("CoahuilaRelacion.Api.Models.DeclaracionFecha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeclaracionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoFecha")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeclaracionId");

                    b.ToTable("DeclaracionFechas");
                });

            modelBuilder.Entity("CoahuilaRelacion.Api.Models.DeclaracionImagen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Angulo")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeclaracionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ElementoRelevante")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaCaptura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("TEXT");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoImagen")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeclaracionId");

                    b.ToTable("DeclaracionImagenes");
                });

            modelBuilder.Entity("CoahuilaRelacion.Api.Models.Registro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ap")
                        .HasColumnType("TEXT");

                    b.Property<string>("Declarante")
                        .HasColumnType("TEXT");

                    b.Property<string>("Entrevistado")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Foja")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tomo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("Numero");

                    b.ToTable("Registros");
                });

            modelBuilder.Entity("CoahuilaRelacion.Api.Models.Declaracion", b =>
                {
                    b.HasOne("CoahuilaRelacion.Api.Models.Registro", "Registro")
                        .WithMany("Declaraciones")
                        .HasForeignKey("RegistroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registro");
                });

            modelBuilder.Entity("CoahuilaRelacion.Api.Models.DeclaracionCoordenada", b =>
                {
                    b.HasOne("CoahuilaRelacion.Api.Models.Declaracion", "Declaracion")
                        .WithMany("Coordenadas")
                        .HasForeignKey("DeclaracionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Declaracion");
                });

            modelBuilder.Entity("CoahuilaRelacion.Api.Models.DeclaracionFecha", b =>
                {
                    b.HasOne("CoahuilaRelacion.Api.Models.Declaracion", "Declaracion")
                        .WithMany("Fechas")
                        .HasForeignKey("DeclaracionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Declaracion");
                });

            modelBuilder.Entity("CoahuilaRelacion.Api.Models.DeclaracionImagen", b =>
                {
                    b.HasOne("CoahuilaRelacion.Api.Models.Declaracion", "Declaracion")
                        .WithMany("Imagenes")
                        .HasForeignKey("DeclaracionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Declaracion");
                });

            modelBuilder.Entity("CoahuilaRelacion.Api.Models.Declaracion", b =>
                {
                    b.Navigation("Coordenadas");

                    b.Navigation("Fechas");

                    b.Navigation("Imagenes");
                });

            modelBuilder.Entity("CoahuilaRelacion.Api.Models.Registro", b =>
                {
                    b.Navigation("Declaraciones");
                });
#pragma warning restore 612, 618
        }
    }
}
