// <auto-generated />
using System;
using CoahuilaRelacion.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoahuilaRelacion.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414165053_AddRelaciones")]
    partial class AddRelaciones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CoahuilaRelacion.Api.Models.Actor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreNormalizado")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notas")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NombreNormalizado");

                    b.ToTable("Actores");
                });

            modelBuilder.Entity("CoahuilaRelacion.Api.Models.Circunstancia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreNormalizado")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NombreNormalizado");

                    b.ToTable("Circunstancias");
                });

            modelBuilder.Entity("CoahuilaRelacion.Api.Models.Declaracion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaCaptura")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RegistroId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextoDeclaracion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Orden");

                    b.HasIndex("RegistroId");

                    b.ToTable("Declaraciones");
                });

            modelBuilder.Entity("CoahuilaRelacion.Api.Models.DeclaracionActor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Confianza")
                        .HasColumnType("REAL");

                    b.Property<bool>("Confirmado")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DeclaracionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origen")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("DeclaracionId", "ActorId")
                        .IsUnique();

                    b.ToTable("DeclaracionActores");
                });

            modelBuilder.Entity("CoahuilaRelacion.Api.Models.DeclaracionCircunstancia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CircunstanciaId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Confianza")
                        .HasColumnType("REAL");

                    b.Property<bool>("Confirmado")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DeclaracionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origen")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CircunstanciaId");

                    b.HasIndex("DeclaracionId", "CircunstanciaId")
                        .IsUnique();

                    b.ToTable("DeclaracionCircunstancias");
                });

            modelBuilder.Entity("CoahuilaRelacion.Api.Models.DeclaracionCoordenada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeclaracionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fuente")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitud")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitud")
                        .HasColumnType("REAL");

                    b.Property<string>("Observacion")
                        .HasColumnType("TEXT");

                    b.Property<double?>("PrecisionM")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DeclaracionId");

                    b.ToTable("DeclaracionCoordenadas");
                });

            modelBuilder.Entity("CoahuilaRelacion.Api.Models.DeclaracionFecha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeclaracionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoFecha")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeclaracionId");

                    b.ToTable("DeclaracionFechas");
                });

            modelBuilder.Entity("CoahuilaRelacion.Api.Models.DeclaracionImagen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeclaracionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ElementoRelevante")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaCaptura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("TEXT");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoImagen")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeclaracionId");

                    b.ToTable("DeclaracionImagenes");
                });

            modelBuilder.Entity("CoahuilaRelacion.Api.Models.DeclaracionLugar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Confianza")
                        .HasColumnType("REAL");

                    b.Property<bool>("Confirmado")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DeclaracionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LugarId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origen")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LugarId");

                    b.HasIndex("DeclaracionId", "LugarId")
                        .IsUnique();

                    b.ToTable("DeclaracionLugares");
                });

            modelBuilder.Entity("CoahuilaRelacion.Api.Models.Lugar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Municipio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreNormalizado")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notas")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NombreNormalizado");

                    b.ToTable("Lugares");
                });

            modelBuilder.Entity("CoahuilaRelacion.Api.Models.Registro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ap")
                        .HasColumnType("TEXT");

                    b.Property<string>("Declarante")
                        .HasColumnType("TEXT");

                    b.Property<string>("Entrevistado")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Foja")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tomo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("Numero");

                    b.ToTable("Registros");
                });

            modelBuilder.Entity("CoahuilaRelacion.Api.Models.Declaracion", b =>
                {
                    b.HasOne("CoahuilaRelacion.Api.Models.Registro", "Registro")
                        .WithMany("Declaraciones")
                        .HasForeignKey("RegistroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registro");
                });

            modelBuilder.Entity("CoahuilaRelacion.Api.Models.DeclaracionActor", b =>
                {
                    b.HasOne("CoahuilaRelacion.Api.Models.Actor", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoahuilaRelacion.Api.Models.Declaracion", "Declaracion")
                        .WithMany("Actores")
                        .HasForeignKey("DeclaracionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Declaracion");
                });

            modelBuilder.Entity("CoahuilaRelacion.Api.Models.DeclaracionCircunstancia", b =>
                {
                    b.HasOne("CoahuilaRelacion.Api.Models.Circunstancia", "Circunstancia")
                        .WithMany()
                        .HasForeignKey("CircunstanciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoahuilaRelacion.Api.Models.Declaracion", "Declaracion")
                        .WithMany("Circunstancias")
                        .HasForeignKey("DeclaracionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Circunstancia");

                    b.Navigation("Declaracion");
                });

            modelBuilder.Entity("CoahuilaRelacion.Api.Models.DeclaracionCoordenada", b =>
                {
                    b.HasOne("CoahuilaRelacion.Api.Models.Declaracion", "Declaracion")
                        .WithMany("Coordenadas")
                        .HasForeignKey("DeclaracionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Declaracion");
                });

            modelBuilder.Entity("CoahuilaRelacion.Api.Models.DeclaracionFecha", b =>
                {
                    b.HasOne("CoahuilaRelacion.Api.Models.Declaracion", "Declaracion")
                        .WithMany("Fechas")
                        .HasForeignKey("DeclaracionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Declaracion");
                });

            modelBuilder.Entity("CoahuilaRelacion.Api.Models.DeclaracionImagen", b =>
                {
                    b.HasOne("CoahuilaRelacion.Api.Models.Declaracion", "Declaracion")
                        .WithMany("Imagenes")
                        .HasForeignKey("DeclaracionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Declaracion");
                });

            modelBuilder.Entity("CoahuilaRelacion.Api.Models.DeclaracionLugar", b =>
                {
                    b.HasOne("CoahuilaRelacion.Api.Models.Declaracion", "Declaracion")
                        .WithMany("Lugares")
                        .HasForeignKey("DeclaracionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoahuilaRelacion.Api.Models.Lugar", "Lugar")
                        .WithMany()
                        .HasForeignKey("LugarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Declaracion");

                    b.Navigation("Lugar");
                });

            modelBuilder.Entity("CoahuilaRelacion.Api.Models.Declaracion", b =>
                {
                    b.Navigation("Actores");

                    b.Navigation("Circunstancias");

                    b.Navigation("Coordenadas");

                    b.Navigation("Fechas");

                    b.Navigation("Imagenes");

                    b.Navigation("Lugares");
                });

            modelBuilder.Entity("CoahuilaRelacion.Api.Models.Registro", b =>
                {
                    b.Navigation("Declaraciones");
                });
#pragma warning restore 612, 618
        }
    }
}
